### ISSUE TITLE
Add The Meme Hustler to the history of OSS section?

### ISSUE THREAD

**Issue by federicomenaquintero** [DEGoodmanWilson/Ethical-Resources#3]
Hi,

I don't know if you are interested in suggestions for bibliography, but here goes.

https://thebaffler.com/salvos/the-meme-hustler is a very good, opinionated article on the early history of Open Source.  I think it helps shed some light on why it got popular vs. Free Software.

**Comment by UncannyBingo** [comment]
Yasss! That’s a great one, I love that article. Thank you!
